### ISSUE TITLE
slider widget in template not refresh imediatly

### ISSUE THREAD

**Issue by fab33** [openhab/org.openhab.ui.habpanel#232] opened 2017-10-10 21:04 UTC
Hi,
If we create a template widget with widget-slider and we don't show it at startup but with a ng-show, when widget is displayed value is correct but we have to wait few second before the round dot goes to the right place.
Apparently it's a common "issue" : 
https://github.com/angular-slider/angularjs-slider (see first common issue)
I'm totally newbie with angular so sorry but I can't provide a PR.

**Comment by ghys** [comment] 2017-10-11 14:09
Which version are you using? 2.1 or a recent snapshot?
This might be either caused or fixed by https://github.com/openhab/org.openhab.ui.habpanel/pull/214.

**Comment by DarkLite1** [comment] 2017-10-12 16:36
Sorry for hijacking, but I don't know if this is related or not and couldn't find anything in the issue list. But when you have a volume slider widget on HABpanel, and you slide the volume up or down, it's not immediately executed by the speakers. It's only applied when the slider has stopped moving. I don't know if this by design, but it's a bit annoying. Happens on v. 2.1.

**Comment by fab33** [comment] 2017-10-13 13:46
@ghys I'm using 2.1, I ask here : https://community.openhab.org/t/new-display-options-incl-experimental-custom-widgets-everywhere/34140/5 how to switch only habpanel (openhab 2.2 is sometimes too buggy but habpanel is not critical for me if there are several bugs)

**Comment by ghys** [comment] 2017-10-13 15:47
@fab33 Then I believe #214 is a fix for that (it delays the slider until the view is ready). Not a perfect or even good solution, but this was the best I found to this long standing issue.

Refer to https://community.openhab.org/t/how-to-update-habpanel-only/32303 for a way to update HABPanel without updating your whole openHAB distribution.

> Sorry for hijacking, but I don't know if this is related or not [...] you slide the volume up or down, it's not immediately executed by the speakers. It's only applied when the slider has stopped moving. I don't know if this is by design

Completely unrelated, and yes it's the intended behavior.

**Closed by ghys** 2017-10-13 15:47 UTC
Labels: more info needed

**Comment by fab33** [comment] 2017-10-13 20:43
It's not ok. The slider is on a "popup" div. First time we show the popup, slider appaers after some time with the good value but the next time, slider value is ok but slider position takes about 2 or 3 seconds to be on the correct place.
```
  <div ng-repeat="item in itemsInGroup('gLights')">
    
    <div class="widget" ng-if="item.type=='Color' && itemValue(item.name + '_rgb')=='0,0,0'" ng-click="showHueSelect = !showHueSelect">
      <div class="icon off"><svg viewBox="0 0 48 48"><use xlink:href="/static/matrix-theme/symbol-defs.svg#icon-switch-off"></use></svg></div>
      <div class="name"><div class="hue" ng-style="{'background': 'rgb(' + itemValue(item.name + '_rgb') + ')'}"></div>
        <div class="hueSelect" ng-init="showHueSelect = false" ng-show="showHueSelect"><div class="hueSelectItem"></div>
          <div class="hueSelectOptions">
            <a href="" ng-click="sendCmd(item.name, '0')">
            <svg viewBox="0 0 48 48" style="stroke: white; stroke-width: 3px;"><use xlink:href="/static/matrix-theme/matrixicons.svg#cross-line"></use></svg>
            </a>
            <a href="" ng-click="sendCmd(item.name, color.hsb)" ng-repeat="color in hueColors" ng-style="{ 'background': color.hex }"></a>
            <div ng-init='model={"item": item.name, "floor": 0, "ceil": 100, "step":1}'>
              <widget-slider ng-model="model" />
            </div>
          </div>
        </div>{{item.label}}</div>
    </div>

    <div class="widget" ng-if="item.type=='Color' && itemValue(item.name + '_rgb')!='0,0,0'" ng-click="showHueSelect = !showHueSelect">
      <div class="icon on"><svg viewBox="0 0 48 48"><use xlink:href="/static/matrix-theme/symbol-defs.svg#icon-switch-on"></use></svg></div>
      <div class="name"><div class="hue" ng-style="{'background': 'rgb(' + itemValue(item.name + '_rgb') + ')'}"></div>
        <div class="hueSelect" ng-init="showHueSelect = false" ng-show="showHueSelect"><div class="hueSelectItem"></div>
          <div class="hueSelectOptions">
            <a href="" ng-click="sendCmd(item.name, '0')">
              <svg viewBox="0 0 48 48" style="stroke: white; stroke-width: 3px;"><use xlink:href="/static/matrix-theme/matrixicons.svg#cross-line"></use></svg>
            </a>
            <a href="" ng-click="sendCmd(item.name, color.hsb)" ng-repeat="color in hueColors" ng-style="{ 'background': color.hex }"></a>
            <div ng-init='model={"item": item.name, "floor": 0, "ceil": 100, "step":1}'>
              <widget-slider ng-model="model" />
            </div>
          </div>
        </div>{{item.label}} {{itemValue(item.name).split(',')[2]}}</div>
    </div>

    <div class="widget" ng-if="item.type=='Switch' && itemValue(item.name)=='OFF'" ng-click="sendCmd(item.name, 'ON')">
      <div class="icon off" ><svg viewBox="0 0 48 48"><use xlink:href="/static/matrix-theme/matrixicons.svg#off"></use></svg></div>
      <div class="name">{{item.label}}</div>
    </div>

    <div class="widget" ng-if="item.type=='Switch' && itemValue(item.name)=='ON'" ng-click="sendCmd(item.name, 'OFF')">
      <div class="icon on" ><svg viewBox="0 0 48 48"><use xlink:href="/static/matrix-theme/matrixicons.svg#on"></use></svg></div>
      <div class="name">{{item.label}}</div>
    </div>

    <div class="widget" ng-if="item.type=='Switch' && itemValue(item.name)=='NULL'" ng-click="sendCmd(item.name, 'ON')">
      <div class="icon off" ><svg viewBox="0 0 48 48"><use xlink:href="/static/matrix-theme/matrixicons.svg#none"></use></svg></div>
      <div class="name">{{item.label}}</div>
    </div>
    
  </div>

  </div>
</div>

```
This is made with ppmk theme.

**Comment by ghys** [comment] 2017-10-14 00:26
Maybe try `ng-if` instead of `ng-show`?

**Comment by fab33** [comment] 2017-10-14 09:09
It works but slider takes few seconds to be visible.

**Comment by ghys** [comment] 2017-10-18 14:55
I see. That's because the slider waits for the first refresh event to display with this update.
If you want to open a modal, check the _Opening a modal with sliders for each item in a group_ in https://community.openhab.org/t/habpanel-development-advanced-features-start-here/30755.
If you change your code to something similar to this it will normally work because an update is triggered after `openModal()` is called.

**Comment by fab33** [comment] 2017-10-18 15:09
Ok I will try. Thank you Yannick

**Comment by fab33** [comment] 2017-11-10 21:20
I look your example but it's not working when we want to show an element and not using openModal. The slider documentation and example explain wich funtion to call when showing the concerned html div. Is it possible to implement a such thing or how to call updatevalue() function (if it works !) ?

**Comment by cailleute** [comment] 2018-03-16 12:56
Hello @fab33, did you succeed fixing this issue? I'm still stuck making it work on my IOS device. This code is working on my PC (sorry I don't know how to format the code on this post).
`<div class="hueSelect" ng-init="showHueSelect = false" ng-show="showHueSelect">
            <div class="hueSelectItem"></div>
            <div class="hueSelectOptions">
              <a href="" ng-click="sendCmd(item.name, 'OFF')"><svg viewBox="0 0 48 48" style="stroke: white; stroke-width: 3px;"><use xlink:href="/static/matrix-theme/matrixicons.svg#cross-line"></use></svg></a>
              
              <div ng-init="slider = { value: 0, options: { floor: 0, ceil: 100, step: 1, showSelectionBar: true } };"></div>
              <rzslider rz-slider-model="slider.value" rz-slider-options="slider.options" ng-click="sendCmd(item.name, slider.value)"></rzslider>`

and this one work partially on IOS.
`<div class="hueSelect" ng-init="showHueSelect = false" ng-show="showHueSelect">
            <div class="hueSelectItem"></div>
            <div class="hueSelectOptions">
              <a href="" ng-click="sendCmd(item.name, 'OFF')"><svg viewBox="0 0 48 48" style="stroke: white; stroke-width: 3px;"><use xlink:href="/static/matrix-theme/matrixicons.svg#cross-line"></use></svg></a>
              
              <div ng-init='model={"item": item.name, "floor": 0, "ceil": 100, "step":1}'></div>
              <widget-slider ng-model="model" /> `

Do you have any advice for me? Thanks!

**Comment by jesperldk** [comment] 2019-02-03 15:30
Uh, I have this exact issue on 2.3.
In a fairly complex popup, the sliders does not update until an StateChangeEvent happens in OpenHAP. It seems that HabPanel receives the event and then updates all sliders. Well, actually I also have the same problem in Switches.
I have tried writing it just like in _Opening a modal with sliders for each item in a group_ example in https://community.openhab.org/t/habpanel-development-advanced-features-start-here/30755. And also with different variations. With some variations a few more widgets works.
Seems to be some very basic timing problem. It really is a bummer :-(
I know this issue is closed, but it seems to be exactly the same issue. I am not sure how to open this issues, so I will also open a new.
