### ISSUE TITLE
use locale for date/time

### ISSUE THREAD

**Issue by fab33** [openhab/org.openhab.ui.habpanel#241] opened 2017-10-29 10:19 UTC
According to this : https://code.angularjs.org/1.3.0-rc.2/docs/guide/i18n
If I try : 
{{itemValue('Leaf_LastUpdated') | date:'dd MMMM yyyy @ HH:mm'}}
MMMM is in English and I want to use french locale.
Openhab locale in PaperUI is set to fr-FR, is set on my debian system too and in my browser.

**Comment by ghys** [comment] 2017-10-29 10:45
There's an additional file to load for AngularJS to display the desired locale, this should be done according to the locale configured in openHAB.
I have it on my list ;)

I'm closing this as a duplicate of/related to #131.

Thanks!

**Closed by ghys** 2017-10-29 10:45 UTC
