### ISSUE TITLE
Mapping not working after Auto Update

### ISSUE THREAD

**Issue by samuel-puschacher** [openhab/org.openhab.ui.habpanel#154] opened 2017-02-19 17:17 UTC
I am using the Mapping, to translate the English data from the weather provider to german with the 'de_weather.map'
The Data Are displayed in a Template widget.
`{{itemValue('Condition0_de')}}`
The item configuration: `String  Condition0_de      "Condition [MAP(de_weather.map):%s]"      {weather="locationId=myhome, forecast=0,type=condition, property=text"}
`
When Starting the Panel This works very well
![grafik](https://cloud.githubusercontent.com/assets/9848082/23104514/aef3a82e-f6cf-11e6-8d72-fe8003ef8630.png)

But after the data has automatically refreshed, only the english text is displayed

![grafik](https://cloud.githubusercontent.com/assets/9848082/23104471/cc77faae-f6ce-11e6-8158-24bfa7609920.png)

**Comment by ghys** [comment] 2017-02-23 15:13
@samuel-puschacher  Sorry for the delay.
The root cause of this problem is discussed in https://github.com/eclipse/smarthome/issues/2788 - the mapping will probably not be performed even in the initial call in the future...! Others have managed to translate raw values directly in the template, using a Javascript object acting as a dictionary. See: https://community.openhab.org/t/template-example-weather-binding/15869/69

I'll close this as it's not directly HABPanel-related.
Cheers

**Closed by ghys** 2017-02-23 15:13 UTC
