### ISSUE TITLE
locale settings don't work

### ISSUE THREAD

**Issue by Pirx99** [openhab/org.openhab.ui.habpanel#161] opened 2017-03-14 07:01 UTC
I'm trying to use German localization to let e.g. date expressions like months or days of week be displayed in German. But after all it is still english.  The following statement in a widget 
`<div> {{itemValue('DateTime_item') | date:'dd. MMMM yyyy HH:mm'}} </div>`
will deliver "17. **March** 2017 07:54" which is still English 

So what is wrong?

FYI: I'm running openHAB on Rasbian. The localization is set to DE, so the command `ls` is delivering dates in my local language.
I've also changed two localization parameters in _runtime.cfg_ properly:
```
org.eclipse.smarthome.core.localeprovider:language=de
org.eclipse.smarthome.core.localeprovider:region=DE
```

As the result openHAB is showing the correct locale "de-DE" at start-up ...

Have I missed anything?

**Comment by ghys** [comment] 2017-03-28 18:04
For now HABPanel is only available in English, including date/time formats. AngularJS has [its own system](https://docs.angularjs.org/guide/i18n) for i18n/l10n. There is a separate issue (#131) for this, the main problem would be which locales to include and how to load them dynamically according to the openHAB configuration (which happens to be already loaded by HABPanel, the speech support needs it).
It's definitely on the roadmap though.

So I'm closing this issue as a duplicate of #131. Thanks!

**Closed by ghys** 2017-03-28 18:04 UTC
